import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SiteNoticeContainer from "../../components/SiteNoticeContainer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const forceOpen = process.env.NEXT_PUBLIC_FORCE_NOTICE_DEV === "1";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <SiteNoticeContainer forceOpen={forceOpen} />
        {children}
      </body>
    </html>
  );
}